[package]
authors = ["WillBooster Inc."]
autoexamples = false
categories = ["parser-implementations", "parsing", "text-editors"]
description = "TypeScript and TSX grammars for tree-sitter"
edition = "2024"
keywords = ["incremental", "parsing", "tree-sitter", "typescript", "tsx"]
license = "MIT"
name = "willbooster-tree-sitter-typescript"
readme = "README.md"
repository = "https://github.com/WillBooster/tree-sitter-typescript"
version = "0.0.0"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "common/*",
  "typescript/grammar.js",
  "typescript/src/*",
  "tsx/grammar.js",
  "tsx/src/*",
  "/tree-sitter.json",
  "/queries/*.scm",
  "/javascript/queries/*.scm",
  "/LICENSE",
]

[lib]
name = "tree_sitter_typescript"
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = { package = "willbooster-tree-sitter", version = "1.4.0" }
